services:
  bitcoin:
    image: bitcoin/bitcoin:latest
    container_name: bitcoin
    ports:
      - "18443:18443"  # JSON-RPC port
      - "18444:18444"  # P2P port
    networks:
      - net
    command:
      -printtoconsole
      -regtest=1
      -rpcallowip=0.0.0.0/0  # Allow connections from any IP
      -rpcbind=0.0.0.0       # Bind to all network interfaces
      -rpcauth=bobby:0207fa532832367468c64e747c95e0b2$e9246affabe158e177c0ebc11a74b37fc14b9700664d7fe76f8ceeccd8692938

  nodejs:
    build:
      context: ./nodejs
    container_name: nodejs
    ports:
      - "3000:3000"  # Your application's port
    networks:
      - net
    depends_on:
      - bitcoin

networks:
  net:
    driver: bridge
