volumes:
  bitcoind-data:
    driver: local

services:
  bitcoind:
    image: ruimarinho/bitcoin-core:latest
    container_name: bitcoind
    command: bitcoind -regtest -printtoconsole -server -rpcallowip=0.0.0.0/0
    volumes:
      - bitcoind-data:/home/bitcoin/.bitcoin
      - ./bitcoin.conf:/home/bitcoin/.bitcoin/bitcoin.conf  # Mount your local bitcoin.conf file
    network_mode: host  # Use the host network

  nodejs:
    build: .
    container_name: nodejs
    environment:
      - NETWORK=regtest
      - RPC_USER=bitcoinuser
      - RPC_PASSWORD=bitcoinpassword
    ports:
      - "3333:3333"  # Port for the Node.js app
    network_mode: host  # Use the host network