services:
  bitcoind:
    image: bitcoindevelopernetwork/bitcoind-regtest
    container_name: bitcoind-node
    command: bitcoind -regtest -printtoconsole -rpcallowip=0.0.0.0/0 -rpcbind=0.0.0.0 -server
    ports:
      - "18444:18444"  # P2P network port for regtest
      - "127.0.0.1:18332:18332"  # RPC port, only accessible from localhost
    volumes:
      - bitcoind-data:/bitcoin
    restart: unless-stopped
    networks:
      - bitcoin-network

  node-app:
    build: .
    container_name: nodejs
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    environment:
      - RPC_USER=bitcoinuser
      - RPC_PASSWORD=bitcoinpassword
    ports:
      - "3333:3333"  # Port for the Node.js app
    depends_on:
      - bitcoind
    restart: unless-stopped
    networks:
      - bitcoin-network

volumes:
  bitcoind-data:
    driver: local

networks:
  bitcoin-network:
    driver: bridge
