volumes:
  bitcoind-data:
    driver: local

services:
  bitcoind:
    image: ruimarinho/bitcoin-core:latest
    container_name: bitcoind
    command: bitcoind -regtest -printtoconsole -rpcallowip=0.0.0.0/0 -rpcbind=0.0.0.0 -server -rpcuser=bitcoinuser -rpcpassword=bitcoinpassword
    ports:
      - "18444:18444"  # P2P network port for regtest
      - "18335:18335"  # RPC port, accessible from all IPs
    volumes:
      - bitcoind-data:/home/bitcoin/.bitcoin
      - ./bitcoin.conf:/home/bitcoin/.bitcoin/bitcoin.conf  # Mount your local bitcoin.conf file
    restart: unless-stopped

  nodejs:
    build: .
    container_name: nodejs
    environment:
      - HOST=bitcoind
      - NETWORK=regtest
      - PORT=18335
      - RPC_USER=bitcoinuser
      - RPC_PASSWORD=bitcoinpassword
    ports:
      - "3333:3333"  # Port for the Node.js app
    depends_on:
      - bitcoind
    restart: unless-stopped