networks:
  net:
    driver: bridge

volumes:
  bitcoind-data:
    driver: local

services:
  bitcoind:
    image: ruimarinho/bitcoin-core:latest
    container_name: bitcoind-node
    command: bitcoind -regtest -printtoconsole -rpcallowip=0.0.0.0/0 -rpcbind=0.0.0.0 -server
    ports:
      - "18444:18444"  # P2P network port for regtest
      - "18332:18332"  # RPC port, accessible from all IPs
    volumes:
      - bitcoind-data:/bitcoin
    restart: unless-stopped
    networks:
      - net

  node-app:
    build: .
    container_name: nodejs
    environment:
      - RPC_USER=bitcoinuser
      - RPC_PASSWORD=bitcoinpassword
    ports:
      - "3333:3333"  # Port for the Node.js app
    depends_on:
      - bitcoind
    restart: unless-stopped
    networks:
      - net
