volumes:
  bitcoind-data:
    driver: local

services:
  bitcoind:
    image: ruimarinho/bitcoin-core:latest
    container_name: bitcoind
    command: bitcoind
    ports:
      - "18444:18444"  # P2P network port for regtest
      - "18332:18335"  # RPC port, accessible from all IPs
    volumes:
      - bitcoind-data:/bitcoin
      - ./bitcoin.conf:/root/.bitcoin/bitcoin.conf
    restart: unless-stopped

  nodejs:
    build: .
    container_name: nodejs
    environment:
      - RPC_URL=bitcoind:18335
      - RPC_USER=bitcoinuser
      - RPC_PASSWORD=bitcoinpassword
    ports:
      - "3333:3333"  # Port for the Node.js app
    depends_on:
      - bitcoind
    restart: unless-stopped